apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stet.fullname" . }}-profiles
  labels:
    {{- include "stet.labels" . | nindent 4 }}
data:
{{- range $name, $content := .Values.config.profiles }}
  {{ $name }}: |-
{{ $content | indent 4 }}
{{- end }}
{{- if .Values.config.adapters }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stet.fullname" . }}-adapters
  labels:
    {{- include "stet.labels" . | nindent 4 }}
data:
{{- range $name, $content := .Values.config.adapters }}
  {{ $name }}: |-
{{ $content | indent 4 }}
{{- end }}
{{- end }}
